### ISSUE TITLE
csvtowdm timezone error with datetime format

### ISSUE THREAD

**Issue by icprbcoop** [timcera/wdmtoolbox#34]
Hi, 
Thanks for this tool, which has been useful in handling wdm files for HSPF. 
I am trying to write a csv file (excerpt below) to a wdm and I am getting the timezone error below. Is the datetime format not compatible with the csvtowdm tool?
**Command:**
_wdmtoolbox.csvtowdm(dir_path+'/DIV_PM7_4580_4820.wdm', 3057, start_date=1/1/2023, end_date=12/31/2023, force_freq=None, clean=True, input_ts='df.csv')_

**Input: df.csv**

![dfcsv](https://user-images.githubusercontent.com/33635796/232843960-caba825b-eb18-4809-b62d-38bee95926af.png)

**Error:**
---------------------------------------------------------------------------
UnknownTimeZoneError                      Traceback (most recent call last)
Cell In[38], line 9
      6 df.to_csv('df.csv', index=False, header=None, columns=['datetime','PM7_4820_0001'])
      7 #df.set_index('datetime')
      8 #wdmtoolbox.csvtowdm(dir_path+'/DIV_PM7_4580_4820.wdm', 3057, start_date=1/1/2023, end_date=12/31/2023, force_freq=None, input_ts=df,2)
----> 9 wdmtoolbox.csvtowdm(dir_path+'/DIV_PM7_4580_4820.wdm', 3057, start_date=1/1/2023, end_date=12/31/2023, force_freq=None, clean=True, input_ts='df.csv')

File ~\AppData\Local\anaconda3\lib\site-packages\wdmtoolbox\wdmtoolbox.py:656, in csvtowdm(wdmpath, dsn, start_date, end_date, columns, force_freq, groupby, round_index, clean, target_units, source_units, input_ts)
    618 @program.command(formatter_class=RSTHelpFormatter)
    619 @tsutils.doc(_common_docs)
    620 def csvtowdm(
   (...)
    632     input_ts="-",
    633 ):
    634     """Write data from a CSV file to a DSN.
    635 
    636     File can have comma separated
   (...)
    654     ${source_units}
    655     """
--> 656     tsd = tsutils.common_kwds(
    657         input_ts,
    658         start_date=start_date,
    659         end_date=end_date,
    660         pick=columns,
    661         force_freq=force_freq,
    662         groupby=groupby,
    663         round_index=round_index,
    664         clean=clean,
    665         target_units=target_units,
    666         source_units=source_units,
    667     )
    669     if len(tsd.columns) > 1:
    670         raise ValueError(
    671             tsutils.error_wrapper(
    672                 f"""
   (...)
    676             )
    677         )

File ~\AppData\Local\anaconda3\lib\site-packages\toolbox_utils\tsutils.py:1569, in transform_args.<locals>.transform_args_decorator.<locals>.transform_args_wrapper(*args, **kwargs)
   1564     val_of_argname.arguments[argname] = trans_func(
   1565         val_of_argname.arguments[argname]
   1566     )
   1567 # apply transform functions to argument values
-> 1569 return func(*val_of_argname.args, **val_of_argname.kwargs)

File ~\AppData\Local\anaconda3\lib\site-packages\pydantic\decorator.py:40, in pydantic.decorator.validate_arguments.validate.wrapper_function()

File ~\AppData\Local\anaconda3\lib\site-packages\pydantic\decorator.py:134, in pydantic.decorator.ValidatedFunction.call()

File ~\AppData\Local\anaconda3\lib\site-packages\pydantic\decorator.py:206, in pydantic.decorator.ValidatedFunction.execute()

File ~\AppData\Local\anaconda3\lib\site-packages\toolbox_utils\tsutils.py:1663, in common_kwds(input_tsd, start_date, end_date, pick, force_freq, groupby, dropna, round_index, clean, target_units, source_units, source_units_required, bestfreq, parse_dates, extended_columns, skiprows, index_type, names, usecols, por)
   1660 if por or force_freq:
   1661     dropna = "no"
-> 1663 ntsd = read_iso_ts(
   1664     input_tsd,
   1665     parse_dates=parse_dates,
   1666     extended_columns=extended_columns,
   1667     dropna=dropna,
   1668     skiprows=skiprows,
   1669     index_type=index_type,
   1670     usecols=usecols,
   1671     clean=clean,
   1672 )
   1674 if names is not None:
   1675     ntsd.columns = names

File ~\AppData\Local\anaconda3\lib\site-packages\pydantic\decorator.py:40, in pydantic.decorator.validate_arguments.validate.wrapper_function()

File ~\AppData\Local\anaconda3\lib\site-packages\pydantic\decorator.py:134, in pydantic.decorator.ValidatedFunction.call()

File ~\AppData\Local\anaconda3\lib\site-packages\pydantic\decorator.py:195, in pydantic.decorator.ValidatedFunction.execute()

File ~\AppData\Local\anaconda3\lib\site-packages\toolbox_utils\tsutils.py:2592, in read_iso_ts(dropna, extended_columns, parse_dates, skiprows, index_type, names, header, sep, index_col, usecols, *inindat, **kwds)
   2590 if len(words) > 1:
   2591     with suppress(TypeError):
-> 2592         res.index = res.index.tz_localize(words[1])
   2593     res.index.name = f"Datetime:{words[1]}"
   2594 else:

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py:281, in DatetimeIndex.tz_localize(self, tz, ambiguous, nonexistent)
    279 @doc(DatetimeArray.tz_localize)
    280 def tz_localize(self, tz, ambiguous="raise", nonexistent="raise") -> DatetimeIndex:
--> 281     arr = self._data.tz_localize(tz, ambiguous, nonexistent)
    282     return type(self)._simple_new(arr, name=self.name)

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\core\arrays\_mixins.py:85, in ravel_compat.<locals>.method(self, *args, **kwargs)
     82 @wraps(meth)
     83 def method(self, *args, **kwargs):
     84     if self.ndim == 1:
---> 85         return meth(self, *args, **kwargs)
     87     flags = self._ndarray.flags
     88     flat = self.ravel("K")

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:984, in DatetimeArray.tz_localize(self, tz, ambiguous, nonexistent)
    982         raise TypeError("Already tz-aware, use tz_convert to convert.")
    983 else:
--> 984     tz = timezones.maybe_get_tz(tz)
    985     # Convert to UTC
    987     new_dates = tzconversion.tz_localize_to_utc(
    988         self.asi8,
    989         tz,
   (...)
    992         reso=self._reso,
    993     )

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timezones.pyx:149, in pandas._libs.tslibs.timezones.maybe_get_tz()

File ~\AppData\Local\anaconda3\lib\site-packages\pandas\_libs\tslibs\timezones.pyx:172, in pandas._libs.tslibs.timezones.maybe_get_tz()

File ~\AppData\Local\anaconda3\lib\site-packages\pytz\__init__.py:188, in timezone(zone)
    186             fp.close()
    187     else:
--> 188         raise UnknownTimeZoneError(zone)
    190 return _tzinfo_cache[zone]

UnknownTimeZoneError: '00'

Thanks,
Alimatou Seck

**Comment by timcera** [comment]
I need to make a better error message for this problem.  Right now wdmtoolbox requires a one-line header in the csv file.  It can be as simple as "Datetime, Value".  

I allow for the time zone to be specified in the header by using ":" as a delimiter.  So you can do something like "Datetime:UTC, Value".  With "1984-01-01 00:00:00,0.0" as the first line, wdmtoolbox thinks that "1984-01-01 00:00:00" is the name of the datetime index and the the second ":" delimited field which is "00" is supposed to be a time zone.  Hence the error.

**Comment by icprbcoop** [comment]
Ha, that makes sense. Thanks! 
I will add the appropriate header to the .csv file.

Alimatou
