### ISSUE TITLE
pint.compat issue while running wdmtoolbox

### ISSUE THREAD

**Issue by mishranurag** [timcera/wdmtoolbox#36]
I installed wdmtoolbox on a new installation and came across the following error when I try to import wdmtoolbox. I tested it with Python 3.8, 3.9, and 3.11 and all had same issues.

![image](https://user-images.githubusercontent.com/15083239/236388973-358b3061-9de6-4de9-8c85-3d05f5fe5702.png)

**Comment by timcera** [comment]
Anurag, thank you!

Looks like https://github.com/hgrecco/pint-pandas/issues/168 might be the problem.  I will have to do some more investigation to limit the pint and/or pint_pandas version.

Kind regards,
Tim

**Comment by mishranurag** [comment]
Thanks Tim. It looks like tsgettoolbox also has the same issue.

**Comment by timcera** [comment]
Updated toolbox_utils to version 3.0.5 which will downgrade pint.  This fixes both wdmtoolbox and tsgettoolbox.

`pip install --upgrade toolbox_utils
`

Will downgrade pint from 0.21 to 0.20.1

**Comment by mishranurag** [comment]
Thanks @timcera I really appreciate it.
