### ISSUE TITLE
Saving Latitude and Longitude Attributes while creating New dataset

### ISSUE THREAD

**Issue by mishranurag** [timcera/wdmtoolbox#5]
WDM file supports many attributes and I think Latitude and Longitude are important attributes. It would be useful to have an option of providing these attributes when creating a DSN.

**Comment by timcera** [comment]
As of https://github.com/timcera/wdmtoolbox/commit/56bb8c6cdd39e443efc2ba679386918d11212d37 has a "setattrib" function to set any attribute and "describedsn" has a new option to list all attributes.
