### ISSUE TITLE
Installation Issues for Python3.12

### ISSUE THREAD

**Issue by mishranurag** [timcera/wdmtoolbox#52]
Hi Tim

I am trying to install wdmtoolbox on Python3.12. The conda installtion keeps trying to resolve but never completes. The pip installation exits with the message below.

Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Thank you

**Comment by timcera** [comment]
Anurag,

No wdmtoolbox yet for python 3.12.  Haunted by this problem https://numpy.org/doc/stable/reference/distutils_status_migration.html 

Tried to move to meson, but still no luck yet with supporting 3.12.
