### ISSUE TITLE
Pre-compiled installation fails on windows.

### ISSUE THREAD

**Issue by thodson-usgs** [timcera/wdmtoolbox#7]
Something is missing from the Windows installation instructions. I followed them to the letter, but I'm getting an error upon import.
(https://timcera.bitbucket.io/wdmtoolbox/docsrc/install.html)

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\thodson\Miniconda3\envs\py39\lib\site-packages\wdmtoolbox\wdmutil.py", line 22, in <module>
    import _wdm_lib
ImportError: DLL load failed while importing _wdm_lib: The specified module could not be found.`

**Comment by timcera** [comment]
This is fixed in 12.8.0 which I just uploaded to pypi.
